// - LOGIN
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CONFIG_PROFILE = 'CONFIG_PROFILE';
export const SET_FIREBASE_TOKEN = 'SET_FIREBASE_TOKEN';
export const SET_USER_DATA = 'SET_USER_DATA';

//APPLICATION
export const CHANGE_FONT = 'CHANGE_FONT';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const INCREMENT_LOADING = 'INCREMENT_LOADING';
export const DECREMENT_LOADING = 'DECREMENT_LOADING';
export const RESET_LOADING = 'RESET_LOADING';
